### PR TITLE
Updates for pro agent (#108)

### PR DESCRIPTION
**Pull request by xnerhu**
* Update README.md

* Update some signals and add type exports

* Remove duplicate signals and fix lint

### CODE REVIEW

**Comment by tvvocold** [comment]
hi @xnerhu, plz update the `npm` to v1.3.0 as well.

**Comment by xnerhu** [comment]
@tvvocold It's on npm now.

**Comment by tvvocold** [comment]
> @tvvocold It's on npm now.

plz update the CDN's file as well: https://openfpcdn.io/botd/v1

**Comment by xnerhu** [comment]
> > @tvvocold It's on npm now.
> 
> plz update the CDN's file as well: https://openfpcdn.io/botd/v1

CDN always updates automatically once the package is available on NPM.

**Pull request merged**
