### PR TITLE
Export BotResult along with BotKind

### PR DESCRIPTION
**Pull request by xnerhu**

### CODE REVIEW

**Comment by xnerhu** [comment]
@Finesse I had to replace `const enum BotKind` with `enum BotKind`, because of 
```
dist/botd.d.ts:192:30 - error TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided
```

Let me know if that's ok and won't have side effects on CDN.

**Comment by xnerhu** [comment]
another approach would be to use string union instead of enum

**Review by Finesse — APPROVED** [review]
I'm sure there will be no problems with Open CDN. It handles only the distributive JS code.

```
dist/botd.d.ts:192:30 - error TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided
```

TypeScript makes sure the package won't cause problems for users who use `--isolatedModules`. When an enum is not const, it's available in the JS runtime, which might be handy for JS users.

> another approach would be to use string union instead of enum

It's a good option. But only TS users will be able to use the `BotKind` type.

**Comment by Finesse** [comment]
> For the sake of consistency I changed const enum to enum in the entire project

@xnerhu Up to you. I see no technical problems.

The reasons to prefers const enums are:

- Hiding the value names in the minified code (not a concern here since it's open-source)
- Reducing the minified code size by not including the value names (it affects Pro agent, but it's minor)

If you think the consistency is more important, no problem.

**Comment by xnerhu** [comment]
Thanks for the review, I will merge it now.

**Review by Finesse — APPROVED** [review]

**Pull request merged**
